import polars as pl

monitor_json_schema = {
    'state_code': pl.Utf8,
    'country_code': pl.Utf8,
    'site_number': pl.Utf8,
    'poc': pl.Int64,
    'parameter_name': pl.Utf8,
    'open_date': pl.Utf8,
    'close_date': pl.Utf8,
    'concurred_exclusions': pl.Utf8,
    'dominant_source': pl.Utf8,
    'measurement_scale': pl.Utf8,
    'measurement_scale_def': pl.Utf8,
    'monitoring_objective': pl.Utf8,
    'last_method_description': pl.Utf8,
    'last_method_begin_date': pl.Utf8,
    'naaqs_primary_monitor': pl.Utf8,
    'qa_primary_monitor': pl.Utf8,
    'monitor_type': pl.Utf8,
    'networks': pl.Utf8,
    'monitoring_agency_code': pl.Utf8,
    'monitoring_agency': pl.Utf8,
    'si_id': pl.Int64,
    'latitude': pl.Float64,
    'longitude': pl.Float64,
    'datum': pl.Utf8,
    'lat_lon_accuracy': pl.Float64,
    'elevation': pl.Int64,
    'probe_height': pl.Float64,
    'pl_probe_location': pl.Utf8,
    'local_site_name': pl.Utf8,
    'address': pl.Utf8,
    'state_name': pl.Utf8,
    'county_name': pl.Utf8,
    'city_name': pl.Utf8,
    'cbsa_code': pl.Utf8,
    'cbsa_name': pl.Utf8,
    'csa_code': pl.Utf8,
    'csa_name': pl.Utf8,
    'tribal_code': pl.Utf8,
    'tribe_name': pl.Utf8
}