from polars import Utf8, Float64, Int64

monitor_json_schema = {
    'state_code': Utf8,
    'country_code': Utf8,
    'site_number': Utf8,
    'poc': Int64,
    'parameter_name': Utf8,
    'open_date': Utf8,
    'close_date': Utf8,
    'concurred_exclusions': Utf8,
    'dominant_source': Utf8,
    'measurement_scale': Utf8,
    'measurement_scale_def': Utf8,
    'monitoring_objective': Utf8,
    'last_method_description': Utf8,
    'last_method_begin_date': Utf8,
    'naaqs_primary_monitor': Utf8,
    'qa_primary_monitor': Utf8,
    'monitor_type': Utf8,
    'networks': Utf8,
    'monitoring_agency_code': Utf8,
    'monitoring_agency': Utf8,
    'si_id': Int64,
    'latitude': Float64,
    'longitude': Float64,
    'datum': Utf8,
    'lat_lon_accuracy': Float64,
    'elevation': Int64,
    'probe_height': Float64,
    'pl_probe_location': Utf8,
    'local_site_name': Utf8,
    'address': Utf8,
    'state_name': Utf8,
    'county_name': Utf8,
    'city_name': Utf8,
    'cbsa_code': Utf8,
    'cbsa_name': Utf8,
    'csa_code': Utf8,
    'csa_name': Utf8,
    'tribal_code': Utf8,
    'tribe_name': Utf8
}

sample_json_schema = {
    'state_code': Utf8,
    'county_code': Utf8,
    'site_number': Utf8,
    'parameter_code': Utf8,
    'poc': Int64,
    'latitude': Float64,
    'longitude': Float64,
    'datum': Utf8,
    'parameter': Utf8,
    'date_local': Utf8,
    'time_local': Utf8,
    'date_gmt': Utf8,
    'time_gmt': Utf8,
    'sample_measurement': Float64,
    'units_of_measure': Utf8,
    'units_of_measure_code': Utf8,
    'sample_duration': Utf8,
    'sample_duration_code': Utf8,
    'sample_frequency': Utf8,
    'detection_limit': Float64,
    'uncertainty': Utf8,
    'qualifier': Utf8,
    'method_type': Utf8,
    'method': Utf8,
    'method_code': Utf8,
    'state': Utf8,
    'county': Utf8,
    'date_of_last_change': Utf8,
    'cbsa_code': Utf8
}