version: 2

sources:
  - name: staging
    description: >
      Landing area for raw parquet data coming in from S3 data lake
    database: airnow_aqs
    schema: staging
    tables:
      - name: stg_hourly_data
        description: >
          Staging table containing hourly air quality observations loaded in daily
      - name: stg_reporting_areas
        description: >
          Staging table containing reporting area definitions
      - name: stg_monitoring_sites
        description: >
          Staging table containing information about the monitoring sites that send hourly air quality observations to the EPA
    
models:
  - name: Fact_AQObs
    description: 'Fact table containing hourly air pollutant measurements from monitoring sites around the world'

  - name: Dim_Date
    description: 'Date dimension table'

  - name: Dim_ReportingArea
    description: 'Dimension table for reporting areas for which air pollutants are measured for'
    constraints:
      - type: unique
        columns: [reporting_area_key]
      - type: foreign_key
        expression: analytics.Bridge_ReportingAreas_MonitoringSites (reporting_area_key)

  - name: Dim_MonitoringSite
    description: 'Dimension table for monitoring sites that report air pollutant measurements'
    constraints:
      - type: unique
        columns: [monitoring_site_key]
      - type: foreign_key
        expression: analytics.Bridge_ReportingAreas_MonitoringSites (monitoring_site_key)

  - name: Bridge_ReportingArea_MonitoringSite
    description: 'Bridge table containing mappings of monitoring sites to their respective reporting areas'