version: 2

sources:
  - name: staging
    description: >
      Landing area for raw parquet data coming in from S3 data lake
    database: airnow_aqs
    schema: staging
    tables:
      - name: stg_hourly_data
        description: >
          Staging table containing hourly air quality observations loaded in daily
      - name: stg_reporting_areas
        description: >
          Staging table containing reporting area definitions
      - name: stg_monitoring_sites
        description: >
          Staging table containing information about the monitoring sites that send hourly air quality observations to the EPA
      - name: stg_monitoring_sites_to_reporting_areas
        description: >
          Staging table with mapping information between reporting areas and monitoring sites
    
models:
  - name: Fact_AQObs
    description: 'Fact table containing hourly air pollutant measurements from monitoring sites around the world'

  - name: Dim_Date
    description: 'Date dimension table'
    # columns:
    #   - name: date_key
    #     tests:
    #       - relationships:
    #           to: ref('Fact_AQObs')
    #           field: date_key

  - name: Dim_ReportingArea
    description: 'Dimension table for reporting areas for which air pollutants are measured for'
    # columns:
    #   - name: reporting_area_key
    #     tests:
    #       - relationships:
    #           to: ref('Bridge_MonitoringSite_ReportingArea')
    #           field: reporting_area_key

  - name: Dim_MonitoringSite
    description: 'Dimension table for monitoring sites that report air pollutant measurements'
    # columns:
    #   - name: monitoring_site_key
    #     tests:
    #       - relationships:
    #           to: ref('Bridge_MonitoringSite_ReportingArea')
    #           field: monitoring_site_key

  - name: Bridge_MonitoringSite_ReportingArea
    description: 'Bridge table containing mappings of monitoring sites to their respective reporting areas'