version: 2

sources:
  - name: staging
    description: >
      Landing area for raw parquet data coming in from S3 data lake
    database: airnow_aqs
    schema: staging
    tables:
      - name: stg_hourly_data
        description: >
          Staging table containing hourly air quality observations loaded in daily
      - name: stg_reporting_areas
        description: >
          Staging table containing reporting area definitions
      - name: stg_monitoring_sites
        description: >
          Staging table containing information about the monitoring sites that send hourly air quality observations to the EPA
      - name: stg_monitoring_sites_to_reporting_areas
        description: >
          Staging table with mapping information between reporting areas and monitoring sites
    
models:
  - name: Fact_AQObs
    description: 'Fact table containing hourly air pollutant measurements from monitoring sites around the world'
    # columns:
    #   - name: pm10_aqi
    #     tests:
    #       - not_negative
    #   - name: pm25_aqi
    #     tests:
    #       - not_negative
    #   - name: ozone_aqi
    #     tests: 
    #       - not_negative
    #   - name: no2_aqi
    #     tests:
    #       - not_negative

  - name: Dim_Date
    description: 'Date dimension table'
    columns:
      - name: date_key
        tests:
          - not_null

  - name: Dim_ReportingArea
    description: 'Dimension table for reporting areas for which air pollutants are measured for'
    columns:
      - name: reporting_area_key
        tests:
          - not_null

  - name: Dim_MonitoringSite
    description: 'Dimension table for monitoring sites that report air pollutant measurements'
    columns:
      - name: monitoring_site_key
        tests:
          - not_null

  - name: Bridge_MonitoringSite_ReportingArea
    description: 'Bridge table containing mappings of monitoring sites to their respective reporting areas'